version: '3'
services:
  proxy:
    build: proxy
    links:
      - client:client
      - server:server
    ports:
      - "80:80"
    depends_on:
      - server
      - client
  client:
    build: client
    depends_on:
      - server
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
  server:
    build: server
    ports:
      - "3000:3000"
    environment:
      - API_HOST=localhost
      - API_PORT=3000
